### ISSUE TITLE
Question about downloading pre-generated files

### ISSUE THREAD

**Issue by ahnGeo** [princetonvisualai/HAT#1]
Hello
I've seen your excellent work, and I would like to download the pre-generated kinetics segmentation mask for use. 
However, it's quite challenging to download all the files from the Google Drive link by clicking 400 times individually. Is there a more convenient way to download them? 
Since they are large files, it seems difficult to upload them publicly. For now, I'll leave my email address. 
ahngeo11@khu.ac.kr
I would also like to download the inpainting frames. 
Thank you for your try!

**Comment by a6o** [comment]
Feel free to try third-party programs (e.g, [gdrive3](https://github.com/glotlabs/gdrive)) to download the dataset. In particular, GDrive can be run in command, and download the whole directory in the background.)
